name: Build pulp-fixtures OCI Image

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install pylint
          sudo apt-get install -y shellcheck
      - name: Build & test the image
        run: |
          .ci/build_image.sh
      - name: Display log on error
        if: failure()
        run: docker logs pulp
